# run with "docker compose up -d"
version: '3.7'

services:
  dynamodb:
    image: amazon/dynamodb-local
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./dynamodb-data:/home/dynamodblocal/data
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"

  setup:
    image: amazon/aws-cli
    depends_on:
      - dynamodb
    volumes:
      - ./dynamodb-init:/dynamodb-init
    command: >
      sh -c "aws dynamodb create-table --cli-input-json ./src/main/resources/init.sql --endpoint-url http://dynamodb:8000"
